# def tampilkan_menu():
#     print("█▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀█")
#     print("█                   Menu Edukasi Tentang Sampah                █")
#     print("█ 1. Berita tentang sampah                                     █")
#     print("█ 2. Pengelolaan sampah                                        █")
#     print("█ 3. Kembali ke menu utama                                     █")
#     print("█▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄█\n")

# def menu_pengelolaan():
#     print("█▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀█")
#     print("█               Menu Pengelolaan Tentang Sampah                █")
#     print("█ 1. Sampah organik dan pengelolaannya                         █")
#     print("█ 2. Sampah anorganik dan pengelolaannya                       █")
#     print("█ 3. Kembali ke menu edukasi                                   █")
#     print("█▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄█\n")
        
# def pengelolaan_anorganik() :
#     print("█▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀█")
#     print("█            Menu Cara Pengelolaan Sampah Anorganik            █")
#     print("█ 1. Reuse                                                     █")
#     print("█ 2. Reduce                                                    █")
#     print("█ 3. Recycle                                                   █")
#     print("█ 4. Kembali ke menu pengelolaan                               █")
#     print("█▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄█\n")

# def pengelolaan_sampah():
#     print("█▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀█")
#     print("█                   3R pengelolaan sampah                      █")
#     print("█                                                              █")
#     print("█ Konsep ini memiliki inti yakni Reuse (Menggunakan kembali    █")
#     print("█ sampah sampah yang masih bisa digunakan atau bisa berfungsi  █")
#     print("█ lainnya), Reduce (Mengurangi segala sesuatu yang             █")
#     print("█ mengakibatkan atau memunculkan sampah), Recycle (Mengolah    █")
#     print("█ kembali sampah atau daur ulang menjadi suatu produk atau     █")
#     print("█ barang yang dapat bermanfaat).                               █")                         
#     print("█                                                              █")
#     print("█▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄█\n")

# def berita_sampah():
#     os.system("cls")
#     print("█▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀█")
#     print("█                   Berita Tentang Sampah                      █")
#     print("█                                                              █")
#     print("█ Jogja darurat sampah masih berlanjut hingga hari ini.        █")
#     print("█ Penumpukan sampah yang terjadi di beberapa sudut Kota        █")
#     print("█ Yogyakarta adalah imbas dari sempat ditutupnya tempat        █")
#     print("█ Pengelolaan Akhir (TPA) Piyungan. Walaupun beberapa tempat   █")
#     print("█ sudah dibersihkan, tetapi ada beberapa tempat yang sampahnya █")
#     print("█ masih menggunung. Salah satunya adalah TPS di Terban. TPS    █")
#     print("█ tersebut, terdapat sampah yang menggunung dan sudah menjadi  █")
#     print("█ pemandangan sehari-hari. Tentu hal ini sangat memprihatinkan.█")
#     print("█                                                              █")
#     print("█                                                              █")
#     print("█ Berita dan informasi mengenai sampah terkini dan terbaru     █")
#     print("█ dapat diakses di link berikut:                               █")
#     print("█          https://www.detik.com/tag/sampah/                   █")
#     print("█                                                              █")
#     print("█▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄█\n")

# def sampah_organik():
#     os.system("cls")
#     print("█▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀█")
#     print("█                        Sampah Organik:                       █")
#     print("█                                                              █")
#     print("█ Sampah organik berasal dari sisa-sisa bahan organik yang     █")
#     print("█ dapat terurai. Ini meliputi sisa makanan, dedaunan, dan      █")
#     print("█ material organik lainnya. Dengan memisahkan sampah organik,  █")
#     print("█ kita dapat menghasilkan kompos yang berguna untuk tanah.     █")
#     print("█▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄█")
#     print()
#     print("█▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀█")
#     print("█               Cara Daur Ulang Sampah Organik                 █")
#     print("█                                                              █")
#     print("█ 1. Pengomposan                                               █")
#     print("█    Pengomposan dapat dilakukan di tempat sampah khusus       █")                              
#     print("█    kompos di halaman belakang rumah atau dengan fasilitas    █")                  
#     print("█    berskala lebih besar yaitu menggunakan layanan            █")                  
#     print("█    pengomposan seperti pengangkutan sampah di tepi jalan.    █")                    
#     print("█                                                              █")
#     print("█ 2. Pengomposan Vermik                                        █")
#     print("█    Vermicomposting adalah jenis pengomposan yang menggunakan █")
#     print("█    cacing untuk mengurai sampah organik. Cacing-cacing       █")
#     print("█    tersebut memakan limbah organik dan menghasilkan tanah    █")
#     print("█    yang kaya akan unsur hara.                                █")
#     print("█                                                              █")
#     print("█ 3. Aplikasi Ke Lahan Pertanian                               █")
#     print("█    Limbah organik dapat diaplikasikan pada lahan pertanian   █")
#     print("█    sebagai pembenah tanah dan pupuk. Proses ini membantu     █")
#     print("█    meningkatkan kesehatan dan kesuburan tanah.               █")
#     print("█                                                              █")
#     print("█▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄█\n")
#     print()

# def sampah_anorganik():
#     os.system("cls")
#     print("█▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀█")
#     print("█                      Sampah Anorganik:                       █")
#     print("█                                                              █")
#     print("█ Sampah organik adalah sampah yang sudah tidak dipakai lagi   █")
#     print("█ dan sulit terurai. Sampah anorganik yang tertimbun di tanah  █")
#     print("█ dapat menyebabkan pencemaran tanah karena sampah anorganik   █")
#     print("█ tergolong zat yang sulit terurai dan sampah itu akan         █")
#     print("█ tertimbun dalam tanah dalam waktu yang lama, ini menyebabkan █")
#     print("█ rusaknya lapisan tanah.                                      █")
#     print("█                                                              █")
#     print("█▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄█\n")

# def reuse_anorganik():
#     os.system("cls")
#     print("█▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀█")
#     print("█                       Pengertian Reuse                       █")
#     print("█                                                              █")
#     print("█ adalah konsep untuk menggunakan kembali bahan yang masih     █")
#     print("█ bisa digunakan dan meminimalisir jumlah sampah. Hal ini      █")
#     print("█ dilakukan dengan cara memanfaatkan kembali produk yang       █")
#     print("█ yang sudah tidak digunakan                                   █")
#     print("█▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄█")
#     print()
#     print("█▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀█")
#     print("█           Contoh dan Cara Reuse Sampah Anorganik             █")
#     print("█                                                              █")
#     print("█ 1. Kertas Dan Karton                                         █")
#     print("█    Kertas bekas dapat diolah kembali menjadi kertas baru.    █")     
#     print("█    Kardus dan kertas bekas dapat diubah menjadi kemasan      █")              
#     print("█    baru atau wadah penyimpanan                               █")          
#     print("█                                                              █")                          
#     print("█ 2. Botol Plastik                                             █")
#     print("█    Botol plastik dapat didaur ulang menjadi botol baru       █")
#     print("█    atau produk plastik lainnya. Kemasan plastik dapat        █")
#     print("█     diubah menjadi produk lain, seperti karpet atau          █")
#     print("█    peralatan taman                                           █")
#     print("█                                                              █")
#     print("█ 3. Kain dan Tekstil                                          █")
#     print("█    Pakaian bekas dapat diolah kembali menjadi serat tekstil  █")
#     print("█    untuk membuat pakaian baru. Beberapa organisasi           █")
#     print("█    mengumpulkan dan menjual pakaian bekas yang masih layak   █")
#     print("█    pakai.                                                    █")
#     print("█                                                              █")
#     print("█ 4. Kaca                                                      █")
#     print("█    Botol kaca dan wadah kaca dapat diolah kembali menjadi    █")
#     print("█    kaca baru. Potongan kaca bekas dapat digunakan untuk      █")
#     print("█    membuat karya seni atau kerajinan tangan.                 █")
#     print("█                                                              █")
#     print("█ 5. Kayu Bekas                                                █")
#     print("█    Pallet dan kayu bekas lainnya dapat diolah kembali        █")
#     print("█    menjadi produk kayu baru atau digunakan untuk bahan       █")
#     print("█    konstruksi. Potongan kayu bekas dapat dijadikan bahan     █")
#     print("█    untuk seni dan kerajinan.                                 █")
#     print("█                                                              █")
#     print("█▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄█\n")
    
# def reduce_anorganik():
#     os.system("cls")
#     print("█▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀█")
#     print("█                       Pengertian Reduce                      █")
#     print("█                                                              █")
#     print("█ Prinsip Reduce (kurangi) berarti kita harus berusaha         █")
#     print("█ mengurangi jumlah sampah yang dihasilkan. Hal ini dapat      █")
#     print("█ dilakukan dengan cara menghindari penggunaan barang-barang   █")
#     print("█ yang tidak diperlukan, seperti kantong plastik sekali pakai, █")
#     print("█ botol air minum, dan kemasan makanan sekali pakai            █")
#     print("█▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄█")
#     print()
#     print("█▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀█")
#     print("█                    Reduce Sampah Anorganik                   █")
#     print("█                                                              █")
#     print("█ 1. Kertas Dan Karton                                         █")
#     print("█    Mengurangi Penggunaan Kertas: Menggunakan kertas dengan   █") 
#     print("█    bijak, seperti mencetak di kedua sisi kertas atau         █")
#     print("█    menggunakan email dan dokumen digital untuk mengurangi    █")
#     print("█    konsumsi kertas.                                          █")     
#     print("█                                                              █")        
#     print("█ 2. Botol Plastik                                             █")
#     print("█    Menghindari Plastik Sekali Pakai: Mengurangi konsumsi     █") 
#     print("█    produk plastik sekali pakai, seperti tas plastik atau     █")
#     print("█    botol air, dengan menggunakan barang-barang yang dapat    █")
#     print("█    digunakan berulang kali                                   █")
#     print("█                                                              █")  
#     print("█ 3. Kain dan Tekstil                                          █")
#     print("█    Donasi dan Penjualan Ulang: Mengambil opsi donasi atau    █")
#     print("█    penjualan ulang untuk pakaian bekas yang masih layak      █")
#     print("█    pakai, daripada membuangnya.                              █")
#     print("█                                                              █")
#     print("█ 4. Kaca                                                      █")
#     print("█    Menghindari Pembelian Produk Kaca yang Mudah Pecah:       █")
#     print("█    Memilih produk kaca yang tahan lama dan menghindari       █")
#     print("█    pembelian produk kaca yang mudah pecah untuk mengurangi   █")
#     print("█    limbah kaca.                                              █")
#     print("█                                                              █")
#     print("█ 5. Kayu Bekas                                                █")
#     print("█    Menggunakan Kayu Ramah Lingkungan: Memilih produk         █")
#     print("█    kayu yang berasal dari sumber yang berkelanjutan dan      █")
#     print("█    menghindari pembelian produk kayu yang tidak diperlukan.  █")
#     print("█                                                              █")
#     print("█▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄█\n")
    
# def recycle_anorganik():
#     os.system("cls")
#     print("█▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀█")
#     print("█                       Pengertian Recycle                     █")
#     print("█                                                              █")
#     print("█ prinsip Recycle (daur ulang) berarti kita harus memanfaatkan █")
#     print("█ sampah yang dapat didaur ulang. Sampah yang dapat didaur     █")
#     print("█ ulang meliputi kertas, plastik, logam, dan kaca. Daur ulang  █")
#     print("█ adalah proses pengolahan kembali sampah menjadi bahan baku   █")
#     print("█ baru yang dapat digunakan untuk membuat produk baru.         █")
#     print("█▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄█")
#     print()
#     print("█▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀█")
#     print("█                    Recycle Sampah Anorganik                  █")
#     print("█                                                              █")
#     print("█ 1. Kertas Dan Karton                                         █")
#     print("█    Mengumpulkan dan Mendaur Ulang Kertas: Mengumpulkan       █") 
#     print("█    kertas bekas seperti kertas koran, kardus, atau kertas    █")
#     print("█    kantor, dan mengirimkannya ke fasilitas daur ulang        █")
#     print("█    kertas.                                                   █")                               
#     print("█                                                              █")                                   
#     print("█ 2. Botol Plastik                                             █")
#     print("█    Mengumpulkan dan Mendaur Ulang Plastik: Membuang botol    █") 
#     print("█    plastik, kemasan plastik, atau produk plastik lainnya     █")
#     print("█    di tempat daur ulang yang telah ditentukan.               █")
#     print("█                                                              █")  
#     print("█ 3. Kain dan Tekstil                                          █")
#     print("█    Mendaur Ulang Tekstil: Mengumpulkan pakaian bekas yang    █")
#     print("█    tidak dapat didonasikan atau dijual ulang, dan            █")
#     print("█    mengirimkannya ke fasilitas daur ulang tekstil.           █")
#     print("█                                                              █")
#     print("█ 4. Kaca                                                      █")
#     print("█    Mengumpulkan dan Mendaur Ulang Kaca: Memisahkan botol     █")
#     print("█    kaca dan wadah kaca dari sampah lainnya dan               █")
#     print("█    mengirimkannya ke fasilitas daur ulang kaca               █")                      
#     print("█                                                              █")
#     print("█ 5. Kayu Bekas                                                █")
#     print("█    Mengumpulkan dan Mendaur Ulang Kayu: Memisahkan kayu      █")
#     print("█    bekas seperti pallet atau potongan kayu dari sampah       █")
#     print("█    lainnya dan mengirimkannya ke fasilitas daur ulang kayu.  █")
#     print("█                                                              █")
#     print("█▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄█\n")

# def menu_2_sampah_anorganik():
#     while True :
#         os.system("cls")
#         pengelolaan_sampah()
#         menu_pengelolaan()
#         print("================================================================")
#         print("                     >>>  pilih menu  <<<                 ")
#         submenu = int(input("                               "))
#         print("================================================================\n")
#         if submenu == 1:    
#             sampah_organik()
#             print("================================================================")
#             print("      >>>  tekan enter untuk kembai ke menu pengelolaan  <<<        ")
#             q = input("================================================================\n")
#         elif submenu == 2:
#             while True :
#                 os.system("cls")
#                 sampah_anorganik()
#                 pengelolaan_anorganik()
#                 print("================================================================")
#                 print("                      >>>  pilih menu  <<<                      ")
#                 subsubmenu = int(input("                               "))
#                 print("================================================================\n")
#                 if subsubmenu == 1 :
#                     reuse_anorganik()
#                     print("\n================================================================")
#                     print("      >>>  tekan enter untuk kembai ke menu pengelolaan  <<<        ")
#                     q = input("================================================================\n")
#                 elif subsubmenu == 2 :
#                     reduce_anorganik()
#                     print("\n================================================================")
#                     print("      >>>  tekan enter untuk kembai ke menu pengelolaan  <<<        ")
#                     q = input("================================================================\n")
#                 elif subsubmenu == 3 :
#                     recycle_anorganik()
#                     print("\n================================================================")
#                     print("      >>>  tekan enter untuk kembai ke menu pengelolaan  <<<        ")
#                     q = input("================================================================\n")
#                 elif subsubmenu == 4 :
#                     menu_2_sampah_anorganik()
#                     break
#                 else:
#                     print("\n================================================================")
#                     print("     >>>  Input salah! Masukkan kode input yang benar  <<<   ")
#                     print("================================================================\n")
#                     print("\n================================================================")
#                     print("      >>>  tekan enter untuk kembai ke menu pengelolaan  <<<        ")
#                     q = input("================================================================\n")
#         elif submenu == 3 :
#             main_edukasi()
#             break
#         else:
#             print("\n================================================================")
#             print("     >>>  Input salah! Masukkan kode input yang benar  <<<      ")
#             print("================================================================\n")
#             print("\n================================================================")
#             print("      >>>  tekan enter untuk kembai ke menu pengelolaan  <<<        ")
#             q = input("================================================================\n")

# def main_edukasi():
#     while True:
#         os.system("cls")
#         tampilkan_menu()
#         print("================================================================")
#         print("                     >>>  pilih menu  <<<                 ")
#         pilihan = int(input("                               "))
#         print("================================================================\n")
#         if pilihan == 1:
#             berita_sampah()
#             print("\n================================================================")
#             print("        >>>  tekan enter untuk kembai ke menu edukasi  <<<        ")
#             q = input("================================================================\n")

#         elif pilihan == 2 :
#             menu_2_sampah_anorganik()
#             break
            
#         elif pilihan == 3 :
#             os.system("cls")
#             print("================================================================")
#             print("|                                                              |")
#             print("|      Terima kasih telah membaca edukasi dari TrashWise       |")
#             print("|     Semoga edukasi yang kami berikan bisa selalu berguna     |")
#             print("|  Teruslah bersama kami dalam menciptakan perubahan positif!  |")
#             print("|                           😁😁                               |")
#             print("|                                                              |")
#             print("|                      Sampai jumpa lagi!                      |")
#             print("|                                                              |")
#             print("================================================================")
#             print("")
#             print("================================================================")        
#             print("        >>>  Tekan enter untuk kembali ke menu utama <<<          ")
#             print("================================================================")
#             back = input(" ")
#             break
            

#         else:
#             print("\n================================================================")
#             print("     >>>  Input salah! Masukkan kode input yang benar  <<<   ")
#             print("================================================================\n")
#             print("\n================================================================")
#             print("        >>>  tekan enter untuk kembai ke menu edukasi  <<<        ")
#             q = input("================================================================\n")
            
        
